### ISSUE TITLE
Gatsby 2 version not available on NPM

### ISSUE THREAD

**Issue by jp887** [marcobiedermann/gatsby-plugin-svg-sprite#7]
I'm migrating my site over to Gatsby V2 and it seems that although a pull request has been merged to add support for Gatsby V2, the only package published to npm is the V1 version.

**Comment by deshiknaves** [comment]
+1 Please publish the package

**Comment by deshiknaves** [comment]
Is this project maintained?

**Comment by yn5** [comment]
@marcobiedermann Could you publish the latest version to npm or consider to give somebody else the rights to do that maybe?

**Comment by marcobiedermann** [comment]
@jp887 @deshiknaves @yn5 

Sorry for the long delay.
Just published version `2.0.0` on npm: https://www.npmjs.com/package/gatsby-plugin-svg-sprite

**Comment by yn5** [comment]
Thanks a whole lot @marcobiedermann !
